### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by notqizq** [Scripted1337/Guilded-Token-Creator#1]
it stays like this forever and i tried with rotating proxies and hq proxies
![image](https://user-images.githubusercontent.com/92556879/138574763-a2b9e945-6041-4588-8dda-3e4191849732.png)

**Comment by notqizq** [comment]
> > guilded patched my gen within 1 hour of release 💀
> 
> except it didnt, you just have braindamage, fixed it in like 10 seconds lmfao, and made it faster overall and cleaned up code in like 5 mins

can u send me it pls

**Comment by Scripted1337** [comment]
> 
> 
> > guilded patched my gen within 1 hour of release 💀
> 
> except it didnt, you just have braindamage, fixed it in like 10 seconds lmfao, and made it faster overall and cleaned up code in like 5 mins

proof?

**Comment by Scripted1337** [comment]
> 
> 
> > guilded patched my gen within 1 hour of release 💀
> 
> except it didnt, you just have braindamage, fixed it in like 10 seconds lmfao, and made it faster overall and cleaned up code in like 5 mins

"faster" than the current speed sure sure

**Comment by LunaOnTop** [comment]
> > 
> > 
> > > guilded patched my gen within 1 hour of release 💀
> > 
> > except it didnt, you just have braindamage, fixed it in like 10 seconds lmfao, and made it faster overall and cleaned up code in like 5 mins
> 
> "faster" than the current speed sure sure

you fucked up the thread part.

**Comment by Scripted1337** [comment]
> 
> 
> > > > guilded patched my gen within 1 hour of release 💀
> > > 
> > > 
> > > except it didnt, you just have braindamage, fixed it in like 10 seconds lmfao, and made it faster overall and cleaned up code in like 5 mins
> > 
> > 
> > "faster" than the current speed sure sure
> 
> you fucked up the thread part.

how?

**Comment by LunaOnTop** [comment]
> 
> 
> > > > > guilded patched my gen within 1 hour of release 💀
> > > > 
> > > > 
> > > > except it didnt, you just have braindamage, fixed it in like 10 seconds lmfao, and made it faster overall and cleaned up code in like 5 mins
> > > 
> > > 
> > > "faster" than the current speed sure sure
> > 
> > 
> > you fucked up the thread part.
> 
> how?

when joining them, your joining your joining "t" but just changing to actually being the thread ur using in the for loop, it's faster, also rn im uploading a streamable, so ill show u in a sec its faster

**Comment by LunaOnTop** [comment]
https://streamable.com/nzl1am here's the streamable, also using free proxyscrape proxies, it seems much faster than whatever was in the readme, by looking at the timestamp

**Comment by notqizq** [comment]
> https://streamable.com/nzl1am here's the streamable, also using free proxyscrape proxies, it seems much faster than whatever was in the readme, by looking at the timestamp, changed names to be read from a text file, so it's better for me atleast, it also gets faster over time, upto 10 accounts a second

noice, mind sending me?

**Comment by Scripted1337** [comment]
> 
> 
> https://streamable.com/nzl1am here's the streamable, also using free proxyscrape proxies, it seems much faster than whatever was in the readme, by looking at the timestamp, changed names to be read from a text file, so it's better for me atleast, it also gets faster over time, upto 10 accounts a second

1. u didnt even see the orginal speed of the tool
2. in my knowledge i dont see much of a improvemence other than you printing the name, you said my code wasn't clean which i still dont know why ama just leave this matter here as idc

**Comment by LunaOnTop** [comment]
> 
> 
> > https://streamable.com/nzl1am here's the streamable, also using free proxyscrape proxies, it seems much faster than whatever was in the readme, by looking at the timestamp, changed names to be read from a text file, so it's better for me atleast, it also gets faster over time, upto 10 accounts a second
> 
>     1. u didnt even see the orginal speed of the tool
> 
>     2. in my knowledge i dont see much of a improvemence other than you printing the name, you said my code wasn't clean which i still dont know why ama just leave this matter here as idc

I did see the original speed, as I didn't fix threads before almost finishing changing shit
